// Focused, stable gRPC contract for qoltanba — the operations the service
// actually implements (sign/verify/extract/cert-info/cert-validate), mirroring
// the domain's own types and the REST/CLI JSON contract. It is deliberately
// separate from the aspirational draft api/qoltanba-draft.proto: the domain owns its
// types, and this is one serialization of them.
//
// Binary fields are bytes (base64 in JSON gateways). Times are RFC3339 strings.
// Secrets (password/pin/inline p12) are input-only and never appear in responses.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/qoltanba/v1/service.proto

package qoltanbav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignatureFormat int32

const (
	SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED SignatureFormat = 0
	SignatureFormat_CMS                          SignatureFormat = 1
	SignatureFormat_XML                          SignatureFormat = 2
	SignatureFormat_WSSE                         SignatureFormat = 3
)

// Enum value maps for SignatureFormat.
var (
	SignatureFormat_name = map[int32]string{
		0: "SIGNATURE_FORMAT_UNSPECIFIED",
		1: "CMS",
		2: "XML",
		3: "WSSE",
	}
	SignatureFormat_value = map[string]int32{
		"SIGNATURE_FORMAT_UNSPECIFIED": 0,
		"CMS":                          1,
		"XML":                          2,
		"WSSE":                         3,
	}
)

func (x SignatureFormat) Enum() *SignatureFormat {
	p := new(SignatureFormat)
	*p = x
	return p
}

func (x SignatureFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignatureFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_api_qoltanba_v1_service_proto_enumTypes[0].Descriptor()
}

func (SignatureFormat) Type() protoreflect.EnumType {
	return &file_api_qoltanba_v1_service_proto_enumTypes[0]
}

func (x SignatureFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignatureFormat.Descriptor instead.
func (SignatureFormat) EnumDescriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{0}
}

type CertEncoding int32

const (
	CertEncoding_CERT_ENCODING_UNSPECIFIED CertEncoding = 0
	CertEncoding_PEM                       CertEncoding = 1
	CertEncoding_DER                       CertEncoding = 2
	CertEncoding_BASE64                    CertEncoding = 3
)

// Enum value maps for CertEncoding.
var (
	CertEncoding_name = map[int32]string{
		0: "CERT_ENCODING_UNSPECIFIED",
		1: "PEM",
		2: "DER",
		3: "BASE64",
	}
	CertEncoding_value = map[string]int32{
		"CERT_ENCODING_UNSPECIFIED": 0,
		"PEM":                       1,
		"DER":                       2,
		"BASE64":                    3,
	}
)

func (x CertEncoding) Enum() *CertEncoding {
	p := new(CertEncoding)
	*p = x
	return p
}

func (x CertEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_api_qoltanba_v1_service_proto_enumTypes[1].Descriptor()
}

func (CertEncoding) Type() protoreflect.EnumType {
	return &file_api_qoltanba_v1_service_proto_enumTypes[1]
}

func (x CertEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertEncoding.Descriptor instead.
func (CertEncoding) EnumDescriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{1}
}

type ValidationMethod int32

const (
	ValidationMethod_VALIDATION_METHOD_UNSPECIFIED ValidationMethod = 0
	ValidationMethod_OCSP                          ValidationMethod = 1
	ValidationMethod_CRL                           ValidationMethod = 2
)

// Enum value maps for ValidationMethod.
var (
	ValidationMethod_name = map[int32]string{
		0: "VALIDATION_METHOD_UNSPECIFIED",
		1: "OCSP",
		2: "CRL",
	}
	ValidationMethod_value = map[string]int32{
		"VALIDATION_METHOD_UNSPECIFIED": 0,
		"OCSP":                          1,
		"CRL":                           2,
	}
)

func (x ValidationMethod) Enum() *ValidationMethod {
	p := new(ValidationMethod)
	*p = x
	return p
}

func (x ValidationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_api_qoltanba_v1_service_proto_enumTypes[2].Descriptor()
}

func (ValidationMethod) Type() protoreflect.EnumType {
	return &file_api_qoltanba_v1_service_proto_enumTypes[2]
}

func (x ValidationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationMethod.Descriptor instead.
func (ValidationMethod) EnumDescriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{2}
}

type KeySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*KeySpec_Inline
	//	*KeySpec_Path
	//	*KeySpec_Token
	//	*KeySpec_KeyId
	Source        isKeySpec_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeySpec) Reset() {
	*x = KeySpec{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySpec) ProtoMessage() {}

func (x *KeySpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySpec.ProtoReflect.Descriptor instead.
func (*KeySpec) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *KeySpec) GetSource() isKeySpec_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *KeySpec) GetInline() *InlineKey {
	if x != nil {
		if x, ok := x.Source.(*KeySpec_Inline); ok {
			return x.Inline
		}
	}
	return nil
}

func (x *KeySpec) GetPath() *PathKey {
	if x != nil {
		if x, ok := x.Source.(*KeySpec_Path); ok {
			return x.Path
		}
	}
	return nil
}

func (x *KeySpec) GetToken() *TokenKey {
	if x != nil {
		if x, ok := x.Source.(*KeySpec_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *KeySpec) GetKeyId() string {
	if x != nil {
		if x, ok := x.Source.(*KeySpec_KeyId); ok {
			return x.KeyId
		}
	}
	return ""
}

type isKeySpec_Source interface {
	isKeySpec_Source()
}

type KeySpec_Inline struct {
	Inline *InlineKey `protobuf:"bytes,1,opt,name=inline,proto3,oneof"`
}

type KeySpec_Path struct {
	Path *PathKey `protobuf:"bytes,2,opt,name=path,proto3,oneof"`
}

type KeySpec_Token struct {
	Token *TokenKey `protobuf:"bytes,3,opt,name=token,proto3,oneof"`
}

type KeySpec_KeyId struct {
	KeyId string `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3,oneof"`
}

func (*KeySpec_Inline) isKeySpec_Source() {}

func (*KeySpec_Path) isKeySpec_Source() {}

func (*KeySpec_Token) isKeySpec_Source() {}

func (*KeySpec_KeyId) isKeySpec_Source() {}

type InlineKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P12           []byte                 `protobuf:"bytes,1,opt,name=p12,proto3" json:"p12,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // secret
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineKey) Reset() {
	*x = InlineKey{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineKey) ProtoMessage() {}

func (x *InlineKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineKey.ProtoReflect.Descriptor instead.
func (*InlineKey) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *InlineKey) GetP12() []byte {
	if x != nil {
		return x.P12
	}
	return nil
}

func (x *InlineKey) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *InlineKey) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type PathKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // secret
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathKey) Reset() {
	*x = PathKey{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathKey) ProtoMessage() {}

func (x *PathKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathKey.ProtoReflect.Descriptor instead.
func (*PathKey) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *PathKey) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathKey) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PathKey) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type TokenKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Storage       string                 `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"` // secret
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenKey) Reset() {
	*x = TokenKey{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenKey) ProtoMessage() {}

func (x *TokenKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenKey.ProtoReflect.Descriptor instead.
func (*TokenKey) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *TokenKey) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *TokenKey) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *TokenKey) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type TrustedCert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          []byte                 `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Intermediate  bool                   `protobuf:"varint,2,opt,name=intermediate,proto3" json:"intermediate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustedCert) Reset() {
	*x = TrustedCert{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustedCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustedCert) ProtoMessage() {}

func (x *TrustedCert) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustedCert.ProtoReflect.Descriptor instead.
func (*TrustedCert) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *TrustedCert) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *TrustedCert) GetIntermediate() bool {
	if x != nil {
		return x.Intermediate
	}
	return false
}

type LibError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibError) Reset() {
	*x = LibError{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibError) ProtoMessage() {}

func (x *LibError) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibError.ProtoReflect.Descriptor instead.
func (*LibError) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *LibError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LibError) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Warning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warning) Reset() {
	*x = Warning{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warning) ProtoMessage() {}

func (x *Warning) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warning.ProtoReflect.Descriptor instead.
func (*Warning) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *Warning) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Warning) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SignRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Format            SignatureFormat        `protobuf:"varint,1,opt,name=format,proto3,enum=qoltanba.v1.SignatureFormat" json:"format,omitempty"`
	Data              []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Key               *KeySpec               `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Detached          bool                   `protobuf:"varint,4,opt,name=detached,proto3" json:"detached,omitempty"`
	WithTimestamp     *bool                  `protobuf:"varint,5,opt,name=with_timestamp,json=withTimestamp,proto3,oneof" json:"with_timestamp,omitempty"` // unset → service default
	TsaUrl            string                 `protobuf:"bytes,6,opt,name=tsa_url,json=tsaUrl,proto3" json:"tsa_url,omitempty"`
	NoCheckCertTime   bool                   `protobuf:"varint,7,opt,name=no_check_cert_time,json=noCheckCertTime,proto3" json:"no_check_cert_time,omitempty"`
	InputPem          bool                   `protobuf:"varint,8,opt,name=input_pem,json=inputPem,proto3" json:"input_pem,omitempty"`
	OutputPem         bool                   `protobuf:"varint,9,opt,name=output_pem,json=outputPem,proto3" json:"output_pem,omitempty"`
	NodeId            string                 `protobuf:"bytes,10,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ParentNode        string                 `protobuf:"bytes,11,opt,name=parent_node,json=parentNode,proto3" json:"parent_node,omitempty"`
	ParentNamespace   string                 `protobuf:"bytes,12,opt,name=parent_namespace,json=parentNamespace,proto3" json:"parent_namespace,omitempty"`
	ExistingSignature []byte                 `protobuf:"bytes,13,opt,name=existing_signature,json=existingSignature,proto3" json:"existing_signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *SignRequest) GetFormat() SignatureFormat {
	if x != nil {
		return x.Format
	}
	return SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED
}

func (x *SignRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignRequest) GetKey() *KeySpec {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SignRequest) GetDetached() bool {
	if x != nil {
		return x.Detached
	}
	return false
}

func (x *SignRequest) GetWithTimestamp() bool {
	if x != nil && x.WithTimestamp != nil {
		return *x.WithTimestamp
	}
	return false
}

func (x *SignRequest) GetTsaUrl() string {
	if x != nil {
		return x.TsaUrl
	}
	return ""
}

func (x *SignRequest) GetNoCheckCertTime() bool {
	if x != nil {
		return x.NoCheckCertTime
	}
	return false
}

func (x *SignRequest) GetInputPem() bool {
	if x != nil {
		return x.InputPem
	}
	return false
}

func (x *SignRequest) GetOutputPem() bool {
	if x != nil {
		return x.OutputPem
	}
	return false
}

func (x *SignRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SignRequest) GetParentNode() string {
	if x != nil {
		return x.ParentNode
	}
	return ""
}

func (x *SignRequest) GetParentNamespace() string {
	if x != nil {
		return x.ParentNamespace
	}
	return ""
}

func (x *SignRequest) GetExistingSignature() []byte {
	if x != nil {
		return x.ExistingSignature
	}
	return nil
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Format        SignatureFormat        `protobuf:"varint,2,opt,name=format,proto3,enum=qoltanba.v1.SignatureFormat" json:"format,omitempty"`
	LibError      *LibError              `protobuf:"bytes,3,opt,name=lib_error,json=libError,proto3" json:"lib_error,omitempty"`
	Timestamp     *Timestamp             `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // parsed TSP (CMS) when a timestamp was added
	CadesLevel    string                 `protobuf:"bytes,5,opt,name=cades_level,json=cadesLevel,proto3" json:"cades_level,omitempty"` // BES | T
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *SignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignResponse) GetFormat() SignatureFormat {
	if x != nil {
		return x.Format
	}
	return SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED
}

func (x *SignResponse) GetLibError() *LibError {
	if x != nil {
		return x.LibError
	}
	return nil
}

func (x *SignResponse) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SignResponse) GetCadesLevel() string {
	if x != nil {
		return x.CadesLevel
	}
	return ""
}

type VerifyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Format         SignatureFormat        `protobuf:"varint,1,opt,name=format,proto3,enum=qoltanba.v1.SignatureFormat" json:"format,omitempty"`
	Signature      []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Data           []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Detached       bool                   `protobuf:"varint,4,opt,name=detached,proto3" json:"detached,omitempty"`
	InputPem       bool                   `protobuf:"varint,5,opt,name=input_pem,json=inputPem,proto3" json:"input_pem,omitempty"`
	CheckCertTime  bool                   `protobuf:"varint,6,opt,name=check_cert_time,json=checkCertTime,proto3" json:"check_cert_time,omitempty"`
	ExtractContent bool                   `protobuf:"varint,7,opt,name=extract_content,json=extractContent,proto3" json:"extract_content,omitempty"`
	TrustedCerts   []*TrustedCert         `protobuf:"bytes,8,rep,name=trusted_certs,json=trustedCerts,proto3" json:"trusted_certs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyRequest) GetFormat() SignatureFormat {
	if x != nil {
		return x.Format
	}
	return SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED
}

func (x *VerifyRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *VerifyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VerifyRequest) GetDetached() bool {
	if x != nil {
		return x.Detached
	}
	return false
}

func (x *VerifyRequest) GetInputPem() bool {
	if x != nil {
		return x.InputPem
	}
	return false
}

func (x *VerifyRequest) GetCheckCertTime() bool {
	if x != nil {
		return x.CheckCertTime
	}
	return false
}

func (x *VerifyRequest) GetExtractContent() bool {
	if x != nil {
		return x.ExtractContent
	}
	return false
}

func (x *VerifyRequest) GetTrustedCerts() []*TrustedCert {
	if x != nil {
		return x.TrustedCerts
	}
	return nil
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Format        SignatureFormat        `protobuf:"varint,2,opt,name=format,proto3,enum=qoltanba.v1.SignatureFormat" json:"format,omitempty"`
	Detached      bool                   `protobuf:"varint,3,opt,name=detached,proto3" json:"detached,omitempty"`
	Signers       []*Signer              `protobuf:"bytes,4,rep,name=signers,proto3" json:"signers,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Warnings      []*Warning             `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	LibError      *LibError              `protobuf:"bytes,7,opt,name=lib_error,json=libError,proto3" json:"lib_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyResponse) GetFormat() SignatureFormat {
	if x != nil {
		return x.Format
	}
	return SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED
}

func (x *VerifyResponse) GetDetached() bool {
	if x != nil {
		return x.Detached
	}
	return false
}

func (x *VerifyResponse) GetSigners() []*Signer {
	if x != nil {
		return x.Signers
	}
	return nil
}

func (x *VerifyResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *VerifyResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *VerifyResponse) GetLibError() *LibError {
	if x != nil {
		return x.LibError
	}
	return nil
}

type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        SignatureFormat        `protobuf:"varint,1,opt,name=format,proto3,enum=qoltanba.v1.SignatureFormat" json:"format,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *ExtractRequest) GetFormat() SignatureFormat {
	if x != nil {
		return x.Format
	}
	return SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED
}

func (x *ExtractRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ExtractRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Detached      bool                   `protobuf:"varint,2,opt,name=detached,proto3" json:"detached,omitempty"`
	LibError      *LibError              `protobuf:"bytes,3,opt,name=lib_error,json=libError,proto3" json:"lib_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *ExtractResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ExtractResponse) GetDetached() bool {
	if x != nil {
		return x.Detached
	}
	return false
}

func (x *ExtractResponse) GetLibError() *LibError {
	if x != nil {
		return x.LibError
	}
	return nil
}

type CertInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          []byte                 `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Key           *KeySpec               `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Encoding      CertEncoding           `protobuf:"varint,3,opt,name=encoding,proto3,enum=qoltanba.v1.CertEncoding" json:"encoding,omitempty"`
	BuildChain    bool                   `protobuf:"varint,4,opt,name=build_chain,json=buildChain,proto3" json:"build_chain,omitempty"`
	Validate      bool                   `protobuf:"varint,5,opt,name=validate,proto3" json:"validate,omitempty"`
	Method        ValidationMethod       `protobuf:"varint,6,opt,name=method,proto3,enum=qoltanba.v1.ValidationMethod" json:"method,omitempty"`
	TrustedCerts  []*TrustedCert         `protobuf:"bytes,7,rep,name=trusted_certs,json=trustedCerts,proto3" json:"trusted_certs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertInfoRequest) Reset() {
	*x = CertInfoRequest{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertInfoRequest) ProtoMessage() {}

func (x *CertInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertInfoRequest.ProtoReflect.Descriptor instead.
func (*CertInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *CertInfoRequest) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *CertInfoRequest) GetKey() *KeySpec {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CertInfoRequest) GetEncoding() CertEncoding {
	if x != nil {
		return x.Encoding
	}
	return CertEncoding_CERT_ENCODING_UNSPECIFIED
}

func (x *CertInfoRequest) GetBuildChain() bool {
	if x != nil {
		return x.BuildChain
	}
	return false
}

func (x *CertInfoRequest) GetValidate() bool {
	if x != nil {
		return x.Validate
	}
	return false
}

func (x *CertInfoRequest) GetMethod() ValidationMethod {
	if x != nil {
		return x.Method
	}
	return ValidationMethod_VALIDATION_METHOD_UNSPECIFIED
}

func (x *CertInfoRequest) GetTrustedCerts() []*TrustedCert {
	if x != nil {
		return x.TrustedCerts
	}
	return nil
}

type CertInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *Certificate           `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Chain         []*Certificate         `protobuf:"bytes,2,rep,name=chain,proto3" json:"chain,omitempty"`
	Warnings      []*Warning             `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	LibError      *LibError              `protobuf:"bytes,4,opt,name=lib_error,json=libError,proto3" json:"lib_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertInfoResponse) Reset() {
	*x = CertInfoResponse{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertInfoResponse) ProtoMessage() {}

func (x *CertInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertInfoResponse.ProtoReflect.Descriptor instead.
func (*CertInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *CertInfoResponse) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *CertInfoResponse) GetChain() []*Certificate {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *CertInfoResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *CertInfoResponse) GetLibError() *LibError {
	if x != nil {
		return x.LibError
	}
	return nil
}

type CertValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          []byte                 `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Encoding      CertEncoding           `protobuf:"varint,2,opt,name=encoding,proto3,enum=qoltanba.v1.CertEncoding" json:"encoding,omitempty"`
	Method        ValidationMethod       `protobuf:"varint,3,opt,name=method,proto3,enum=qoltanba.v1.ValidationMethod" json:"method,omitempty"`
	WantOcsp      bool                   `protobuf:"varint,4,opt,name=want_ocsp,json=wantOcsp,proto3" json:"want_ocsp,omitempty"`
	TrustedCerts  []*TrustedCert         `protobuf:"bytes,5,rep,name=trusted_certs,json=trustedCerts,proto3" json:"trusted_certs,omitempty"`
	ResponderUrl  string                 `protobuf:"bytes,6,opt,name=responder_url,json=responderUrl,proto3" json:"responder_url,omitempty"`
	Crl           []byte                 `protobuf:"bytes,7,opt,name=crl,proto3" json:"crl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertValidateRequest) Reset() {
	*x = CertValidateRequest{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertValidateRequest) ProtoMessage() {}

func (x *CertValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertValidateRequest.ProtoReflect.Descriptor instead.
func (*CertValidateRequest) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *CertValidateRequest) GetCert() []byte {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *CertValidateRequest) GetEncoding() CertEncoding {
	if x != nil {
		return x.Encoding
	}
	return CertEncoding_CERT_ENCODING_UNSPECIFIED
}

func (x *CertValidateRequest) GetMethod() ValidationMethod {
	if x != nil {
		return x.Method
	}
	return ValidationMethod_VALIDATION_METHOD_UNSPECIFIED
}

func (x *CertValidateRequest) GetWantOcsp() bool {
	if x != nil {
		return x.WantOcsp
	}
	return false
}

func (x *CertValidateRequest) GetTrustedCerts() []*TrustedCert {
	if x != nil {
		return x.TrustedCerts
	}
	return nil
}

func (x *CertValidateRequest) GetResponderUrl() string {
	if x != nil {
		return x.ResponderUrl
	}
	return ""
}

func (x *CertValidateRequest) GetCrl() []byte {
	if x != nil {
		return x.Crl
	}
	return nil
}

type CertValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *RevocationStatus      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info          string                 `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	OcspResponse  []byte                 `protobuf:"bytes,3,opt,name=ocsp_response,json=ocspResponse,proto3" json:"ocsp_response,omitempty"`
	Warnings      []*Warning             `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	LibError      *LibError              `protobuf:"bytes,5,opt,name=lib_error,json=libError,proto3" json:"lib_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertValidateResponse) Reset() {
	*x = CertValidateResponse{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertValidateResponse) ProtoMessage() {}

func (x *CertValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertValidateResponse.ProtoReflect.Descriptor instead.
func (*CertValidateResponse) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *CertValidateResponse) GetStatus() *RevocationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CertValidateResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *CertValidateResponse) GetOcspResponse() []byte {
	if x != nil {
		return x.OcspResponse
	}
	return nil
}

func (x *CertValidateResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *CertValidateResponse) GetLibError() *LibError {
	if x != nil {
		return x.LibError
	}
	return nil
}

type Subject struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommonName       string                 `protobuf:"bytes,1,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	LastName         string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	GivenName        string                 `protobuf:"bytes,3,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	Email            string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Organization     string                 `protobuf:"bytes,5,opt,name=organization,proto3" json:"organization,omitempty"`
	OrgUnit          string                 `protobuf:"bytes,6,opt,name=org_unit,json=orgUnit,proto3" json:"org_unit,omitempty"`
	Country          string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Locality         string                 `protobuf:"bytes,8,opt,name=locality,proto3" json:"locality,omitempty"`
	State            string                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	BusinessCategory string                 `protobuf:"bytes,10,opt,name=business_category,json=businessCategory,proto3" json:"business_category,omitempty"`
	DomainComponent  string                 `protobuf:"bytes,11,opt,name=domain_component,json=domainComponent,proto3" json:"domain_component,omitempty"`
	Dn               string                 `protobuf:"bytes,12,opt,name=dn,proto3" json:"dn,omitempty"`
	Iin              string                 `protobuf:"bytes,13,opt,name=iin,proto3" json:"iin,omitempty"`
	Bin              string                 `protobuf:"bytes,14,opt,name=bin,proto3" json:"bin,omitempty"`
	Gender           string                 `protobuf:"bytes,15,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *Subject) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *Subject) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Subject) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *Subject) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Subject) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *Subject) GetOrgUnit() string {
	if x != nil {
		return x.OrgUnit
	}
	return ""
}

func (x *Subject) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Subject) GetLocality() string {
	if x != nil {
		return x.Locality
	}
	return ""
}

func (x *Subject) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Subject) GetBusinessCategory() string {
	if x != nil {
		return x.BusinessCategory
	}
	return ""
}

func (x *Subject) GetDomainComponent() string {
	if x != nil {
		return x.DomainComponent
	}
	return ""
}

func (x *Subject) GetDn() string {
	if x != nil {
		return x.Dn
	}
	return ""
}

func (x *Subject) GetIin() string {
	if x != nil {
		return x.Iin
	}
	return ""
}

func (x *Subject) GetBin() string {
	if x != nil {
		return x.Bin
	}
	return ""
}

func (x *Subject) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type Certificate struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Subject               *Subject               `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Issuer                *Subject               `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	SerialNumber          string                 `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	NotBefore             string                 `protobuf:"bytes,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter              string                 `protobuf:"bytes,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	SignatureAlgorithm    string                 `protobuf:"bytes,6,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"`
	SignatureAlgorithmOid string                 `protobuf:"bytes,7,opt,name=signature_algorithm_oid,json=signatureAlgorithmOid,proto3" json:"signature_algorithm_oid,omitempty"`
	KeyAlgorithm          string                 `protobuf:"bytes,8,opt,name=key_algorithm,json=keyAlgorithm,proto3" json:"key_algorithm,omitempty"`
	PublicKey             []byte                 `protobuf:"bytes,9,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AuthorityKeyId        string                 `protobuf:"bytes,10,opt,name=authority_key_id,json=authorityKeyId,proto3" json:"authority_key_id,omitempty"`
	SubjectKeyId          string                 `protobuf:"bytes,11,opt,name=subject_key_id,json=subjectKeyId,proto3" json:"subject_key_id,omitempty"`
	KeyUsage              []string               `protobuf:"bytes,12,rep,name=key_usage,json=keyUsage,proto3" json:"key_usage,omitempty"`
	KeyUsageKind          string                 `protobuf:"bytes,13,opt,name=key_usage_kind,json=keyUsageKind,proto3" json:"key_usage_kind,omitempty"`
	ExtendedKeyUsage      []string               `protobuf:"bytes,14,rep,name=extended_key_usage,json=extendedKeyUsage,proto3" json:"extended_key_usage,omitempty"`
	PolicyOids            []string               `protobuf:"bytes,15,rep,name=policy_oids,json=policyOids,proto3" json:"policy_oids,omitempty"`
	OwnerType             string                 `protobuf:"bytes,16,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	Roles                 []string               `protobuf:"bytes,17,rep,name=roles,proto3" json:"roles,omitempty"`
	CaIssuerUrls          []string               `protobuf:"bytes,18,rep,name=ca_issuer_urls,json=caIssuerUrls,proto3" json:"ca_issuer_urls,omitempty"`
	OcspUrls              []string               `protobuf:"bytes,19,rep,name=ocsp_urls,json=ocspUrls,proto3" json:"ocsp_urls,omitempty"`
	CrlUrls               []string               `protobuf:"bytes,20,rep,name=crl_urls,json=crlUrls,proto3" json:"crl_urls,omitempty"`
	IsCa                  bool                   `protobuf:"varint,21,opt,name=is_ca,json=isCa,proto3" json:"is_ca,omitempty"`
	Pem                   []byte                 `protobuf:"bytes,22,opt,name=pem,proto3" json:"pem,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *Certificate) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Certificate) GetIssuer() *Subject {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *Certificate) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Certificate) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *Certificate) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

func (x *Certificate) GetSignatureAlgorithm() string {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return ""
}

func (x *Certificate) GetSignatureAlgorithmOid() string {
	if x != nil {
		return x.SignatureAlgorithmOid
	}
	return ""
}

func (x *Certificate) GetKeyAlgorithm() string {
	if x != nil {
		return x.KeyAlgorithm
	}
	return ""
}

func (x *Certificate) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Certificate) GetAuthorityKeyId() string {
	if x != nil {
		return x.AuthorityKeyId
	}
	return ""
}

func (x *Certificate) GetSubjectKeyId() string {
	if x != nil {
		return x.SubjectKeyId
	}
	return ""
}

func (x *Certificate) GetKeyUsage() []string {
	if x != nil {
		return x.KeyUsage
	}
	return nil
}

func (x *Certificate) GetKeyUsageKind() string {
	if x != nil {
		return x.KeyUsageKind
	}
	return ""
}

func (x *Certificate) GetExtendedKeyUsage() []string {
	if x != nil {
		return x.ExtendedKeyUsage
	}
	return nil
}

func (x *Certificate) GetPolicyOids() []string {
	if x != nil {
		return x.PolicyOids
	}
	return nil
}

func (x *Certificate) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *Certificate) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Certificate) GetCaIssuerUrls() []string {
	if x != nil {
		return x.CaIssuerUrls
	}
	return nil
}

func (x *Certificate) GetOcspUrls() []string {
	if x != nil {
		return x.OcspUrls
	}
	return nil
}

func (x *Certificate) GetCrlUrls() []string {
	if x != nil {
		return x.CrlUrls
	}
	return nil
}

func (x *Certificate) GetIsCa() bool {
	if x != nil {
		return x.IsCa
	}
	return false
}

func (x *Certificate) GetPem() []byte {
	if x != nil {
		return x.Pem
	}
	return nil
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	GenTime       string                 `protobuf:"bytes,2,opt,name=gen_time,json=genTime,proto3" json:"gen_time,omitempty"`
	Policy        string                 `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	Tsa           string                 `protobuf:"bytes,4,opt,name=tsa,proto3" json:"tsa,omitempty"`
	HashAlgorithm string                 `protobuf:"bytes,5,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"`
	Hash          []byte                 `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *Timestamp) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Timestamp) GetGenTime() string {
	if x != nil {
		return x.GenTime
	}
	return ""
}

func (x *Timestamp) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *Timestamp) GetTsa() string {
	if x != nil {
		return x.Tsa
	}
	return ""
}

func (x *Timestamp) GetHashAlgorithm() string {
	if x != nil {
		return x.HashAlgorithm
	}
	return ""
}

func (x *Timestamp) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Signer struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Certificate             *Certificate           `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Chain                   []*Certificate         `protobuf:"bytes,2,rep,name=chain,proto3" json:"chain,omitempty"`
	Valid                   bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	SigningTime             string                 `protobuf:"bytes,4,opt,name=signing_time,json=signingTime,proto3" json:"signing_time,omitempty"`
	SignatureAlgorithm      string                 `protobuf:"bytes,5,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"`
	Timestamp               *Timestamp             `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainComplete           bool                   `protobuf:"varint,7,opt,name=chain_complete,json=chainComplete,proto3" json:"chain_complete,omitempty"`
	TrustAnchorFound        bool                   `protobuf:"varint,8,opt,name=trust_anchor_found,json=trustAnchorFound,proto3" json:"trust_anchor_found,omitempty"`
	CadesLevel              string                 `protobuf:"bytes,9,opt,name=cades_level,json=cadesLevel,proto3" json:"cades_level,omitempty"`
	VerifyInfo              string                 `protobuf:"bytes,10,opt,name=verify_info,json=verifyInfo,proto3" json:"verify_info,omitempty"`
	ChainSignaturesVerified bool                   `protobuf:"varint,11,opt,name=chain_signatures_verified,json=chainSignaturesVerified,proto3" json:"chain_signatures_verified,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Signer) Reset() {
	*x = Signer{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signer) ProtoMessage() {}

func (x *Signer) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signer.ProtoReflect.Descriptor instead.
func (*Signer) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{20}
}

func (x *Signer) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *Signer) GetChain() []*Certificate {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *Signer) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *Signer) GetSigningTime() string {
	if x != nil {
		return x.SigningTime
	}
	return ""
}

func (x *Signer) GetSignatureAlgorithm() string {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return ""
}

func (x *Signer) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Signer) GetChainComplete() bool {
	if x != nil {
		return x.ChainComplete
	}
	return false
}

func (x *Signer) GetTrustAnchorFound() bool {
	if x != nil {
		return x.TrustAnchorFound
	}
	return false
}

func (x *Signer) GetCadesLevel() string {
	if x != nil {
		return x.CadesLevel
	}
	return ""
}

func (x *Signer) GetVerifyInfo() string {
	if x != nil {
		return x.VerifyInfo
	}
	return ""
}

func (x *Signer) GetChainSignaturesVerified() bool {
	if x != nil {
		return x.ChainSignaturesVerified
	}
	return false
}

type RevocationStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Revoked        bool                   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Method         ValidationMethod       `protobuf:"varint,2,opt,name=method,proto3,enum=qoltanba.v1.ValidationMethod" json:"method,omitempty"`
	RevocationTime string                 `protobuf:"bytes,3,opt,name=revocation_time,json=revocationTime,proto3" json:"revocation_time,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	CheckedAt      string                 `protobuf:"bytes,5,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	LibError       *LibError              `protobuf:"bytes,6,opt,name=lib_error,json=libError,proto3" json:"lib_error,omitempty"`
	ThisUpdate     string                 `protobuf:"bytes,7,opt,name=this_update,json=thisUpdate,proto3" json:"this_update,omitempty"`
	NextUpdate     string                 `protobuf:"bytes,8,opt,name=next_update,json=nextUpdate,proto3" json:"next_update,omitempty"`
	ProducedAt     string                 `protobuf:"bytes,9,opt,name=produced_at,json=producedAt,proto3" json:"produced_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevocationStatus) Reset() {
	*x = RevocationStatus{}
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevocationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevocationStatus) ProtoMessage() {}

func (x *RevocationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_qoltanba_v1_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevocationStatus.ProtoReflect.Descriptor instead.
func (*RevocationStatus) Descriptor() ([]byte, []int) {
	return file_api_qoltanba_v1_service_proto_rawDescGZIP(), []int{21}
}

func (x *RevocationStatus) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *RevocationStatus) GetMethod() ValidationMethod {
	if x != nil {
		return x.Method
	}
	return ValidationMethod_VALIDATION_METHOD_UNSPECIFIED
}

func (x *RevocationStatus) GetRevocationTime() string {
	if x != nil {
		return x.RevocationTime
	}
	return ""
}

func (x *RevocationStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevocationStatus) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

func (x *RevocationStatus) GetLibError() *LibError {
	if x != nil {
		return x.LibError
	}
	return nil
}

func (x *RevocationStatus) GetThisUpdate() string {
	if x != nil {
		return x.ThisUpdate
	}
	return ""
}

func (x *RevocationStatus) GetNextUpdate() string {
	if x != nil {
		return x.NextUpdate
	}
	return ""
}

func (x *RevocationStatus) GetProducedAt() string {
	if x != nil {
		return x.ProducedAt
	}
	return ""
}

var File_api_qoltanba_v1_service_proto protoreflect.FileDescriptor

const file_api_qoltanba_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/qoltanba/v1/service.proto\x12\vqoltanba.v1\"\xb9\x01\n" +
	"\aKeySpec\x120\n" +
	"\x06inline\x18\x01 \x01(\v2\x16.qoltanba.v1.InlineKeyH\x00R\x06inline\x12*\n" +
	"\x04path\x18\x02 \x01(\v2\x14.qoltanba.v1.PathKeyH\x00R\x04path\x12-\n" +
	"\x05token\x18\x03 \x01(\v2\x15.qoltanba.v1.TokenKeyH\x00R\x05token\x12\x17\n" +
	"\x06key_id\x18\x04 \x01(\tH\x00R\x05keyIdB\b\n" +
	"\x06source\"O\n" +
	"\tInlineKey\x12\x10\n" +
	"\x03p12\x18\x01 \x01(\fR\x03p12\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\"O\n" +
	"\aPathKey\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\"L\n" +
	"\bTokenKey\x12\x18\n" +
	"\astorage\x18\x01 \x01(\tR\astorage\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\"E\n" +
	"\vTrustedCert\x12\x12\n" +
	"\x04cert\x18\x01 \x01(\fR\x04cert\x12\"\n" +
	"\fintermediate\x18\x02 \x01(\bR\fintermediate\"2\n" +
	"\bLibError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"7\n" +
	"\aWarning\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xf0\x03\n" +
	"\vSignRequest\x124\n" +
	"\x06format\x18\x01 \x01(\x0e2\x1c.qoltanba.v1.SignatureFormatR\x06format\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12&\n" +
	"\x03key\x18\x03 \x01(\v2\x14.qoltanba.v1.KeySpecR\x03key\x12\x1a\n" +
	"\bdetached\x18\x04 \x01(\bR\bdetached\x12*\n" +
	"\x0ewith_timestamp\x18\x05 \x01(\bH\x00R\rwithTimestamp\x88\x01\x01\x12\x17\n" +
	"\atsa_url\x18\x06 \x01(\tR\x06tsaUrl\x12+\n" +
	"\x12no_check_cert_time\x18\a \x01(\bR\x0fnoCheckCertTime\x12\x1b\n" +
	"\tinput_pem\x18\b \x01(\bR\binputPem\x12\x1d\n" +
	"\n" +
	"output_pem\x18\t \x01(\bR\toutputPem\x12\x17\n" +
	"\anode_id\x18\n" +
	" \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vparent_node\x18\v \x01(\tR\n" +
	"parentNode\x12)\n" +
	"\x10parent_namespace\x18\f \x01(\tR\x0fparentNamespace\x12-\n" +
	"\x12existing_signature\x18\r \x01(\fR\x11existingSignatureB\x11\n" +
	"\x0f_with_timestamp\"\xed\x01\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x124\n" +
	"\x06format\x18\x02 \x01(\x0e2\x1c.qoltanba.v1.SignatureFormatR\x06format\x122\n" +
	"\tlib_error\x18\x03 \x01(\v2\x15.qoltanba.v1.LibErrorR\blibError\x124\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x16.qoltanba.v1.TimestampR\ttimestamp\x12\x1f\n" +
	"\vcades_level\x18\x05 \x01(\tR\n" +
	"cadesLevel\"\xc0\x02\n" +
	"\rVerifyRequest\x124\n" +
	"\x06format\x18\x01 \x01(\x0e2\x1c.qoltanba.v1.SignatureFormatR\x06format\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bdetached\x18\x04 \x01(\bR\bdetached\x12\x1b\n" +
	"\tinput_pem\x18\x05 \x01(\bR\binputPem\x12&\n" +
	"\x0fcheck_cert_time\x18\x06 \x01(\bR\rcheckCertTime\x12'\n" +
	"\x0fextract_content\x18\a \x01(\bR\x0eextractContent\x12=\n" +
	"\rtrusted_certs\x18\b \x03(\v2\x18.qoltanba.v1.TrustedCertR\ftrustedCerts\"\xa7\x02\n" +
	"\x0eVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x124\n" +
	"\x06format\x18\x02 \x01(\x0e2\x1c.qoltanba.v1.SignatureFormatR\x06format\x12\x1a\n" +
	"\bdetached\x18\x03 \x01(\bR\bdetached\x12-\n" +
	"\asigners\x18\x04 \x03(\v2\x13.qoltanba.v1.SignerR\asigners\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x120\n" +
	"\bwarnings\x18\x06 \x03(\v2\x14.qoltanba.v1.WarningR\bwarnings\x122\n" +
	"\tlib_error\x18\a \x01(\v2\x15.qoltanba.v1.LibErrorR\blibError\"x\n" +
	"\x0eExtractRequest\x124\n" +
	"\x06format\x18\x01 \x01(\x0e2\x1c.qoltanba.v1.SignatureFormatR\x06format\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"{\n" +
	"\x0fExtractResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1a\n" +
	"\bdetached\x18\x02 \x01(\bR\bdetached\x122\n" +
	"\tlib_error\x18\x03 \x01(\v2\x15.qoltanba.v1.LibErrorR\blibError\"\xb7\x02\n" +
	"\x0fCertInfoRequest\x12\x12\n" +
	"\x04cert\x18\x01 \x01(\fR\x04cert\x12&\n" +
	"\x03key\x18\x02 \x01(\v2\x14.qoltanba.v1.KeySpecR\x03key\x125\n" +
	"\bencoding\x18\x03 \x01(\x0e2\x19.qoltanba.v1.CertEncodingR\bencoding\x12\x1f\n" +
	"\vbuild_chain\x18\x04 \x01(\bR\n" +
	"buildChain\x12\x1a\n" +
	"\bvalidate\x18\x05 \x01(\bR\bvalidate\x125\n" +
	"\x06method\x18\x06 \x01(\x0e2\x1d.qoltanba.v1.ValidationMethodR\x06method\x12=\n" +
	"\rtrusted_certs\x18\a \x03(\v2\x18.qoltanba.v1.TrustedCertR\ftrustedCerts\"\xe4\x01\n" +
	"\x10CertInfoResponse\x12:\n" +
	"\vcertificate\x18\x01 \x01(\v2\x18.qoltanba.v1.CertificateR\vcertificate\x12.\n" +
	"\x05chain\x18\x02 \x03(\v2\x18.qoltanba.v1.CertificateR\x05chain\x120\n" +
	"\bwarnings\x18\x03 \x03(\v2\x14.qoltanba.v1.WarningR\bwarnings\x122\n" +
	"\tlib_error\x18\x04 \x01(\v2\x15.qoltanba.v1.LibErrorR\blibError\"\xaa\x02\n" +
	"\x13CertValidateRequest\x12\x12\n" +
	"\x04cert\x18\x01 \x01(\fR\x04cert\x125\n" +
	"\bencoding\x18\x02 \x01(\x0e2\x19.qoltanba.v1.CertEncodingR\bencoding\x125\n" +
	"\x06method\x18\x03 \x01(\x0e2\x1d.qoltanba.v1.ValidationMethodR\x06method\x12\x1b\n" +
	"\twant_ocsp\x18\x04 \x01(\bR\bwantOcsp\x12=\n" +
	"\rtrusted_certs\x18\x05 \x03(\v2\x18.qoltanba.v1.TrustedCertR\ftrustedCerts\x12#\n" +
	"\rresponder_url\x18\x06 \x01(\tR\fresponderUrl\x12\x10\n" +
	"\x03crl\x18\a \x01(\fR\x03crl\"\xec\x01\n" +
	"\x14CertValidateResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.qoltanba.v1.RevocationStatusR\x06status\x12\x12\n" +
	"\x04info\x18\x02 \x01(\tR\x04info\x12#\n" +
	"\rocsp_response\x18\x03 \x01(\fR\focspResponse\x120\n" +
	"\bwarnings\x18\x04 \x03(\v2\x14.qoltanba.v1.WarningR\bwarnings\x122\n" +
	"\tlib_error\x18\x05 \x01(\v2\x15.qoltanba.v1.LibErrorR\blibError\"\xab\x03\n" +
	"\aSubject\x12\x1f\n" +
	"\vcommon_name\x18\x01 \x01(\tR\n" +
	"commonName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"given_name\x18\x03 \x01(\tR\tgivenName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\"\n" +
	"\forganization\x18\x05 \x01(\tR\forganization\x12\x19\n" +
	"\borg_unit\x18\x06 \x01(\tR\aorgUnit\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1a\n" +
	"\blocality\x18\b \x01(\tR\blocality\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12+\n" +
	"\x11business_category\x18\n" +
	" \x01(\tR\x10businessCategory\x12)\n" +
	"\x10domain_component\x18\v \x01(\tR\x0fdomainComponent\x12\x0e\n" +
	"\x02dn\x18\f \x01(\tR\x02dn\x12\x10\n" +
	"\x03iin\x18\r \x01(\tR\x03iin\x12\x10\n" +
	"\x03bin\x18\x0e \x01(\tR\x03bin\x12\x16\n" +
	"\x06gender\x18\x0f \x01(\tR\x06gender\"\x95\x06\n" +
	"\vCertificate\x12.\n" +
	"\asubject\x18\x01 \x01(\v2\x14.qoltanba.v1.SubjectR\asubject\x12,\n" +
	"\x06issuer\x18\x02 \x01(\v2\x14.qoltanba.v1.SubjectR\x06issuer\x12#\n" +
	"\rserial_number\x18\x03 \x01(\tR\fserialNumber\x12\x1d\n" +
	"\n" +
	"not_before\x18\x04 \x01(\tR\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x05 \x01(\tR\bnotAfter\x12/\n" +
	"\x13signature_algorithm\x18\x06 \x01(\tR\x12signatureAlgorithm\x126\n" +
	"\x17signature_algorithm_oid\x18\a \x01(\tR\x15signatureAlgorithmOid\x12#\n" +
	"\rkey_algorithm\x18\b \x01(\tR\fkeyAlgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\t \x01(\fR\tpublicKey\x12(\n" +
	"\x10authority_key_id\x18\n" +
	" \x01(\tR\x0eauthorityKeyId\x12$\n" +
	"\x0esubject_key_id\x18\v \x01(\tR\fsubjectKeyId\x12\x1b\n" +
	"\tkey_usage\x18\f \x03(\tR\bkeyUsage\x12$\n" +
	"\x0ekey_usage_kind\x18\r \x01(\tR\fkeyUsageKind\x12,\n" +
	"\x12extended_key_usage\x18\x0e \x03(\tR\x10extendedKeyUsage\x12\x1f\n" +
	"\vpolicy_oids\x18\x0f \x03(\tR\n" +
	"policyOids\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x10 \x01(\tR\townerType\x12\x14\n" +
	"\x05roles\x18\x11 \x03(\tR\x05roles\x12$\n" +
	"\x0eca_issuer_urls\x18\x12 \x03(\tR\fcaIssuerUrls\x12\x1b\n" +
	"\tocsp_urls\x18\x13 \x03(\tR\bocspUrls\x12\x19\n" +
	"\bcrl_urls\x18\x14 \x03(\tR\acrlUrls\x12\x13\n" +
	"\x05is_ca\x18\x15 \x01(\bR\x04isCa\x12\x10\n" +
	"\x03pem\x18\x16 \x01(\fR\x03pem\"\xb0\x01\n" +
	"\tTimestamp\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12\x19\n" +
	"\bgen_time\x18\x02 \x01(\tR\agenTime\x12\x16\n" +
	"\x06policy\x18\x03 \x01(\tR\x06policy\x12\x10\n" +
	"\x03tsa\x18\x04 \x01(\tR\x03tsa\x12%\n" +
	"\x0ehash_algorithm\x18\x05 \x01(\tR\rhashAlgorithm\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\fR\x04hash\"\xe7\x03\n" +
	"\x06Signer\x12:\n" +
	"\vcertificate\x18\x01 \x01(\v2\x18.qoltanba.v1.CertificateR\vcertificate\x12.\n" +
	"\x05chain\x18\x02 \x03(\v2\x18.qoltanba.v1.CertificateR\x05chain\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\x12!\n" +
	"\fsigning_time\x18\x04 \x01(\tR\vsigningTime\x12/\n" +
	"\x13signature_algorithm\x18\x05 \x01(\tR\x12signatureAlgorithm\x124\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x16.qoltanba.v1.TimestampR\ttimestamp\x12%\n" +
	"\x0echain_complete\x18\a \x01(\bR\rchainComplete\x12,\n" +
	"\x12trust_anchor_found\x18\b \x01(\bR\x10trustAnchorFound\x12\x1f\n" +
	"\vcades_level\x18\t \x01(\tR\n" +
	"cadesLevel\x12\x1f\n" +
	"\vverify_info\x18\n" +
	" \x01(\tR\n" +
	"verifyInfo\x12:\n" +
	"\x19chain_signatures_verified\x18\v \x01(\bR\x17chainSignaturesVerified\"\xda\x02\n" +
	"\x10RevocationStatus\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\x125\n" +
	"\x06method\x18\x02 \x01(\x0e2\x1d.qoltanba.v1.ValidationMethodR\x06method\x12'\n" +
	"\x0frevocation_time\x18\x03 \x01(\tR\x0erevocationTime\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x05 \x01(\tR\tcheckedAt\x122\n" +
	"\tlib_error\x18\x06 \x01(\v2\x15.qoltanba.v1.LibErrorR\blibError\x12\x1f\n" +
	"\vthis_update\x18\a \x01(\tR\n" +
	"thisUpdate\x12\x1f\n" +
	"\vnext_update\x18\b \x01(\tR\n" +
	"nextUpdate\x12\x1f\n" +
	"\vproduced_at\x18\t \x01(\tR\n" +
	"producedAt*O\n" +
	"\x0fSignatureFormat\x12 \n" +
	"\x1cSIGNATURE_FORMAT_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03CMS\x10\x01\x12\a\n" +
	"\x03XML\x10\x02\x12\b\n" +
	"\x04WSSE\x10\x03*K\n" +
	"\fCertEncoding\x12\x1d\n" +
	"\x19CERT_ENCODING_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03PEM\x10\x01\x12\a\n" +
	"\x03DER\x10\x02\x12\n" +
	"\n" +
	"\x06BASE64\x10\x03*H\n" +
	"\x10ValidationMethod\x12!\n" +
	"\x1dVALIDATION_METHOD_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04OCSP\x10\x01\x12\a\n" +
	"\x03CRL\x10\x022\xf6\x02\n" +
	"\x10SignatureService\x12;\n" +
	"\x04Sign\x12\x18.qoltanba.v1.SignRequest\x1a\x19.qoltanba.v1.SignResponse\x12A\n" +
	"\x06Verify\x12\x1a.qoltanba.v1.VerifyRequest\x1a\x1b.qoltanba.v1.VerifyResponse\x12D\n" +
	"\aExtract\x12\x1b.qoltanba.v1.ExtractRequest\x1a\x1c.qoltanba.v1.ExtractResponse\x12G\n" +
	"\bCertInfo\x12\x1c.qoltanba.v1.CertInfoRequest\x1a\x1d.qoltanba.v1.CertInfoResponse\x12S\n" +
	"\fCertValidate\x12 .qoltanba.v1.CertValidateRequest\x1a!.qoltanba.v1.CertValidateResponseB7Z5github.com/uelnur/qoltanba/api/qoltanba/v1;qoltanbav1b\x06proto3"

var (
	file_api_qoltanba_v1_service_proto_rawDescOnce sync.Once
	file_api_qoltanba_v1_service_proto_rawDescData []byte
)

func file_api_qoltanba_v1_service_proto_rawDescGZIP() []byte {
	file_api_qoltanba_v1_service_proto_rawDescOnce.Do(func() {
		file_api_qoltanba_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_qoltanba_v1_service_proto_rawDesc), len(file_api_qoltanba_v1_service_proto_rawDesc)))
	})
	return file_api_qoltanba_v1_service_proto_rawDescData
}

var file_api_qoltanba_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_qoltanba_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_qoltanba_v1_service_proto_goTypes = []any{
	(SignatureFormat)(0),         // 0: qoltanba.v1.SignatureFormat
	(CertEncoding)(0),            // 1: qoltanba.v1.CertEncoding
	(ValidationMethod)(0),        // 2: qoltanba.v1.ValidationMethod
	(*KeySpec)(nil),              // 3: qoltanba.v1.KeySpec
	(*InlineKey)(nil),            // 4: qoltanba.v1.InlineKey
	(*PathKey)(nil),              // 5: qoltanba.v1.PathKey
	(*TokenKey)(nil),             // 6: qoltanba.v1.TokenKey
	(*TrustedCert)(nil),          // 7: qoltanba.v1.TrustedCert
	(*LibError)(nil),             // 8: qoltanba.v1.LibError
	(*Warning)(nil),              // 9: qoltanba.v1.Warning
	(*SignRequest)(nil),          // 10: qoltanba.v1.SignRequest
	(*SignResponse)(nil),         // 11: qoltanba.v1.SignResponse
	(*VerifyRequest)(nil),        // 12: qoltanba.v1.VerifyRequest
	(*VerifyResponse)(nil),       // 13: qoltanba.v1.VerifyResponse
	(*ExtractRequest)(nil),       // 14: qoltanba.v1.ExtractRequest
	(*ExtractResponse)(nil),      // 15: qoltanba.v1.ExtractResponse
	(*CertInfoRequest)(nil),      // 16: qoltanba.v1.CertInfoRequest
	(*CertInfoResponse)(nil),     // 17: qoltanba.v1.CertInfoResponse
	(*CertValidateRequest)(nil),  // 18: qoltanba.v1.CertValidateRequest
	(*CertValidateResponse)(nil), // 19: qoltanba.v1.CertValidateResponse
	(*Subject)(nil),              // 20: qoltanba.v1.Subject
	(*Certificate)(nil),          // 21: qoltanba.v1.Certificate
	(*Timestamp)(nil),            // 22: qoltanba.v1.Timestamp
	(*Signer)(nil),               // 23: qoltanba.v1.Signer
	(*RevocationStatus)(nil),     // 24: qoltanba.v1.RevocationStatus
}
var file_api_qoltanba_v1_service_proto_depIdxs = []int32{
	4,  // 0: qoltanba.v1.KeySpec.inline:type_name -> qoltanba.v1.InlineKey
	5,  // 1: qoltanba.v1.KeySpec.path:type_name -> qoltanba.v1.PathKey
	6,  // 2: qoltanba.v1.KeySpec.token:type_name -> qoltanba.v1.TokenKey
	0,  // 3: qoltanba.v1.SignRequest.format:type_name -> qoltanba.v1.SignatureFormat
	3,  // 4: qoltanba.v1.SignRequest.key:type_name -> qoltanba.v1.KeySpec
	0,  // 5: qoltanba.v1.SignResponse.format:type_name -> qoltanba.v1.SignatureFormat
	8,  // 6: qoltanba.v1.SignResponse.lib_error:type_name -> qoltanba.v1.LibError
	22, // 7: qoltanba.v1.SignResponse.timestamp:type_name -> qoltanba.v1.Timestamp
	0,  // 8: qoltanba.v1.VerifyRequest.format:type_name -> qoltanba.v1.SignatureFormat
	7,  // 9: qoltanba.v1.VerifyRequest.trusted_certs:type_name -> qoltanba.v1.TrustedCert
	0,  // 10: qoltanba.v1.VerifyResponse.format:type_name -> qoltanba.v1.SignatureFormat
	23, // 11: qoltanba.v1.VerifyResponse.signers:type_name -> qoltanba.v1.Signer
	9,  // 12: qoltanba.v1.VerifyResponse.warnings:type_name -> qoltanba.v1.Warning
	8,  // 13: qoltanba.v1.VerifyResponse.lib_error:type_name -> qoltanba.v1.LibError
	0,  // 14: qoltanba.v1.ExtractRequest.format:type_name -> qoltanba.v1.SignatureFormat
	8,  // 15: qoltanba.v1.ExtractResponse.lib_error:type_name -> qoltanba.v1.LibError
	3,  // 16: qoltanba.v1.CertInfoRequest.key:type_name -> qoltanba.v1.KeySpec
	1,  // 17: qoltanba.v1.CertInfoRequest.encoding:type_name -> qoltanba.v1.CertEncoding
	2,  // 18: qoltanba.v1.CertInfoRequest.method:type_name -> qoltanba.v1.ValidationMethod
	7,  // 19: qoltanba.v1.CertInfoRequest.trusted_certs:type_name -> qoltanba.v1.TrustedCert
	21, // 20: qoltanba.v1.CertInfoResponse.certificate:type_name -> qoltanba.v1.Certificate
	21, // 21: qoltanba.v1.CertInfoResponse.chain:type_name -> qoltanba.v1.Certificate
	9,  // 22: qoltanba.v1.CertInfoResponse.warnings:type_name -> qoltanba.v1.Warning
	8,  // 23: qoltanba.v1.CertInfoResponse.lib_error:type_name -> qoltanba.v1.LibError
	1,  // 24: qoltanba.v1.CertValidateRequest.encoding:type_name -> qoltanba.v1.CertEncoding
	2,  // 25: qoltanba.v1.CertValidateRequest.method:type_name -> qoltanba.v1.ValidationMethod
	7,  // 26: qoltanba.v1.CertValidateRequest.trusted_certs:type_name -> qoltanba.v1.TrustedCert
	24, // 27: qoltanba.v1.CertValidateResponse.status:type_name -> qoltanba.v1.RevocationStatus
	9,  // 28: qoltanba.v1.CertValidateResponse.warnings:type_name -> qoltanba.v1.Warning
	8,  // 29: qoltanba.v1.CertValidateResponse.lib_error:type_name -> qoltanba.v1.LibError
	20, // 30: qoltanba.v1.Certificate.subject:type_name -> qoltanba.v1.Subject
	20, // 31: qoltanba.v1.Certificate.issuer:type_name -> qoltanba.v1.Subject
	21, // 32: qoltanba.v1.Signer.certificate:type_name -> qoltanba.v1.Certificate
	21, // 33: qoltanba.v1.Signer.chain:type_name -> qoltanba.v1.Certificate
	22, // 34: qoltanba.v1.Signer.timestamp:type_name -> qoltanba.v1.Timestamp
	2,  // 35: qoltanba.v1.RevocationStatus.method:type_name -> qoltanba.v1.ValidationMethod
	8,  // 36: qoltanba.v1.RevocationStatus.lib_error:type_name -> qoltanba.v1.LibError
	10, // 37: qoltanba.v1.SignatureService.Sign:input_type -> qoltanba.v1.SignRequest
	12, // 38: qoltanba.v1.SignatureService.Verify:input_type -> qoltanba.v1.VerifyRequest
	14, // 39: qoltanba.v1.SignatureService.Extract:input_type -> qoltanba.v1.ExtractRequest
	16, // 40: qoltanba.v1.SignatureService.CertInfo:input_type -> qoltanba.v1.CertInfoRequest
	18, // 41: qoltanba.v1.SignatureService.CertValidate:input_type -> qoltanba.v1.CertValidateRequest
	11, // 42: qoltanba.v1.SignatureService.Sign:output_type -> qoltanba.v1.SignResponse
	13, // 43: qoltanba.v1.SignatureService.Verify:output_type -> qoltanba.v1.VerifyResponse
	15, // 44: qoltanba.v1.SignatureService.Extract:output_type -> qoltanba.v1.ExtractResponse
	17, // 45: qoltanba.v1.SignatureService.CertInfo:output_type -> qoltanba.v1.CertInfoResponse
	19, // 46: qoltanba.v1.SignatureService.CertValidate:output_type -> qoltanba.v1.CertValidateResponse
	42, // [42:47] is the sub-list for method output_type
	37, // [37:42] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_api_qoltanba_v1_service_proto_init() }
func file_api_qoltanba_v1_service_proto_init() {
	if File_api_qoltanba_v1_service_proto != nil {
		return
	}
	file_api_qoltanba_v1_service_proto_msgTypes[0].OneofWrappers = []any{
		(*KeySpec_Inline)(nil),
		(*KeySpec_Path)(nil),
		(*KeySpec_Token)(nil),
		(*KeySpec_KeyId)(nil),
	}
	file_api_qoltanba_v1_service_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_qoltanba_v1_service_proto_rawDesc), len(file_api_qoltanba_v1_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_qoltanba_v1_service_proto_goTypes,
		DependencyIndexes: file_api_qoltanba_v1_service_proto_depIdxs,
		EnumInfos:         file_api_qoltanba_v1_service_proto_enumTypes,
		MessageInfos:      file_api_qoltanba_v1_service_proto_msgTypes,
	}.Build()
	File_api_qoltanba_v1_service_proto = out.File
	file_api_qoltanba_v1_service_proto_goTypes = nil
	file_api_qoltanba_v1_service_proto_depIdxs = nil
}
