apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qoltanba.fullname" . }}
  labels:
    {{- include "qoltanba.labels" . | nindent 4 }}
data:
  QOLTANBA_LIB_PATH: {{ printf "%s/%s" .Values.byol.mountPath .Values.byol.libFile | quote }}
  LD_LIBRARY_PATH: {{ .Values.byol.mountPath | quote }}
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
