{{- if .Values.secretConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qoltanba.fullname" . }}
  labels:
    {{- include "qoltanba.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretConfig }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
